### ISSUE TITLE
Hunger Issue

### ISSUE THREAD

**Issue by TBUnivese** [AlmuraDev/Almura#292]
Cooked Chicken Legs only heal half a shank of hunger, supposed to heal 3 shanks. Process is repeatable with any chicken

**Comment by deadoss** [comment]
Issue is now fixed, Cooked chicken legs now restore a full 3 shanks of hunger. Thanks for letting us know!

**Comment by TBUnivese** [comment]
Problem is not fixed, also there are many other food items that have this issue such as: Grapes, Oranges, Handfull of cranberries, lettuce, lambchops, and possibly more that i havent checked

**Comment by deadoss** [comment]
I meant to say it is fixed for the next update.

**Comment by liach** [comment]
@mcsnetworks Close?

**Comment by mcsnetworks** [comment]
No not close.  I need to investigate this as it could appear on Almura 3 as well.

**Comment by deadoss** [comment]
If i remember correctly, All i did to fix this was reference the Minecraft wiki and I believe the problem was the value we had in the hunger parameter: it was 3, but it should have been 6 since each half shank counts as an integer. So i changed the value from 3 to 6 and it healed 3 full shanks.

**Comment by Dockter** [comment]
Resolved in Almura 3.0
